on: [push, workflow_dispatch]

name: CI

jobs:
  build_and_test:
    name: Tests
    strategy:
      # Each arch in the matrix may fail/succeed independently, do not
      # cancel all runs on the first failure
      fail-fast: false
      matrix:
        arch: [Arm64, x86_64, riscv64]
    #runs-on: [self-hosted, linux]
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
